---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flux-system
      version: '>=1.15.0-0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets
  upgrade:
    crds: CreateReplace
