---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAeDeYP2az6MlFmoUevrQUcQD9j3R46p8XNoF/S+b8frgq2nEujicvUnEGF9wVj28So582nm+BUrZuAbJdLqRL3THwwHoYF363zaWnV4racyOpLgCnUUvdsPsevYJ/JbOXeLcgPGk7gw/ZqnTrLG+EtkHfb0iml1JN2SAK4yybBR6agEiVRHh7spHlp/FB4D5Qub33CkPhRMlI0/KgNLWHeP6/GCd9yBFSowKqto0kiM2rQB/vum+Jo51lG1ivlfhuYqjIhTmmLFi/mEdWI3UbUvTObAmboWi4dd4jX4LmjK5cnc/mZVt+uEe7LPFQw7QuPkPbdsfUZk3UmujYwnQ7lJcfeDiBVoSfqOVbt/7jq4ZFv97dTmxrGXXzUXOYIZRml2WzkURKxaIf9sAvQx6DFCB+drBhScjKBNX6GE35dHJy0rNHaJQdmT59UzAhGboaigGmsrGOmZRZr7UfB283OBllNPz7vfBHkijuzD4ys7JK1OLZ3lToBHaincoJeZrKQ4nxlufKGyj3V6SF/bZZNOjB2U0jHGcdW4SvLR3730crU6yOOjPYJ1R/OH22B+1ETrW3uzuy2bcUXjzZE8KkO4+y4t/wktAKVXqkII2WoEO5Uh8ft4sSzsA0tznYfEOmAvYKevgDNt6G5mpUJ1cVZMdlz8u2AszQF8hNdRJb1bPBTuXwGybBBueLwYSD2TBs4U0hHFkHuIsnJ58TwSnsGQw==
    client_secret: AgAfqOXG0UFrx1nfRvyu91rH9W1m8UYYXi4SXAXZq5oVd61KLVDenugSQQCnmHq7hzoSmGnnJD1G9D+USXclmgRTBZ4DMbpP7mlFKjrvwbyuh4lSanqC5BB2OyL6fqWbJoD6Y4r479guKuqybwgbLmpweiZ0tm6NVFweiixw+JY2lPXzFqyvwyj4vOfxt7BAIoKJzz56bSwWE2LKdoz9VKvPmi0QgloTWxTkVCdcBATF2F5o5Vxr6tIlAwFOqtkhJgmqGlWgUle5WITOMg494nkETDmcA2McO0N7pVjVI/BWiKU0gZzTZ0Ek3t8MHqX1s/8UgfTTmAjqKU0OgZPG+iHHZFhVZZn3AXuDh1+2mcWayJnyVW92ouY8HaEVCxtyY47RI54gUfpi5XRzkFge/XAuh7AWsOmIgiQ+dbjS+NYsCMcxL52cUv+Rbc96aRUkbB7eV6hlo2GIi1JAUlR52IikEwMCeN04Td+Oe7ewkTlS6EOKpaxFlkwmYcZsOK6fpyC9LryCSQK5inqVqqUrmIyZgQHrzQSwdwpHEYZ6C9SF9kJFih6TyNjJ5wAh9HDa7sPVnR3vtjCd3TFY4ozj9sshxI02ZCANTmGISZuirMLfn+kAoLYGGmi5ghRiMdT6hNdYjbnsFP0h34eaSLG8qv7gP5xWJCXl44n+Zt5N6YwjTKIpjmjuOvhMdOxz32Si5gx103W8w+ROraGa/73Y9KkcY9O2NoxWTNCAyAP8kDRwxfbp75suSCQjKD5exQh9JjfuCv0s9yfQjaQ8Bq961ls=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
