---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAG4XKt4vwojf1NonhXNh0MV3LeZMOC4YKtkH9ne89oxS3smQRAhwQb9SGG9rmoKkP8inLtNQqKVEF3XJK0lZuII221fRfLqcN6OWyi7Fce1w9+cLOMjeogTUKiCqmrQ7l1e6PqgcuxpTOQ2gvjkCrG5jWmRI3ACqzI/DwfatlTxUkkpYVwWPhbOfElWJOtYzZbMKxds1Ka9vLbDlpcwc+fPKgV2u26KyyPoMxPDC4QM/jTlCEQGxwdmonCeiK3Q6bipca3A7gDNGsrqvU+TH30n7MVFXO/TWWoFzmKcPOrzTga9G7P6MS/2M8Fkufy6HE1aPXcYiOemiDf98izKOJpPv107RznBeYrxFW4KXdjdD7KpIYDkha+YRq52C3q0hmd4GyLR/37tp89lrB0sinqhaZ+wkxQEbERSpoTaU9bPvYVdcfWTW87FayP8sf2sCWQOMRmSDzXBLUQUuHrZFhxW9yByi5VbcTDVW+aoNj1PpNuOwnylDuucT1Se2bnMXDKcGfr1akwFpnxVqnhCbkQ3YmeYt5/lqjxLzVPuQlJ346GaHDFNQTKYOlx12F54tDvoN5CZWVwIVWf5HQvZ9IyB+dHKMOOjH5zsR4J+JPLcVdcDkkwn5iK2TZlxc437fWfPCtDbsmr+fHsqPEX3ZVX/oUknmkUkywlME05cTCPELp/I4n2epl+l2/dSKq33Bx2KtB9uodIz7Nj6Fiqj72Kzw==
    client_secret: AgAUC5ghRmhUnbFZ+3mSH+A98H5GjIMMkxBKzocXEgpf0vYRsRSVoxzkE+4bLmBsZLGFyvK6uHRlxzTRZ3DB0Hc4buG0N9958r9zTN8j6dy9Gaa5kLR5FUeNQ0yBsEP8D7T0fkIwm4s1Uwiu7Vu4en5YulheXjnL7a7VyP/LegUCT6GoMwMNXjWwZiUAlSEsunwtWzXhnl/uvXrqEofevI5ZhJGHE0o40N5+ugq1JKdylFCHA33EFGFn4JKnbiDJXOaeP5WQxVQkJ6nl5mBIkA/c+1dzqExLDSbUohpsBnJ9I9tKyr3PPClZlDSP6nVqzOIxLXqYDbXpYN/FABNC/DqSrURoZEdhxhc3ua1v46ITpNjFLq45VgXIysc+wcc8GgXtmcJR5rmW3G4X3V6dqi3CegaSV+YnkrLI9ou7dD5jHKVygFD7/dEj4wZITgTE8ecl5np1sRWBEfjV65ZFV8ktORg/gDOa/fm/Yjh0GqhORBj/bfIUNT9GJHJ/mnnMEvrlYpyyjDcdPCfbArBu0UPXnLkvHdfWbHmFYJIywZSWRhGOVVqUiYd4h3zB3ZUGtZ3mdPAEfaG0kPOz+vH5HZfs4fmfYtHe4WjxQvwGKpI9OVTyi8WrechXsP3+OQULTxTOqD/nyXz/l203Hn+0yEOR2nCHuJ0kcGS7GMxHJG+WIv0Bra/5F7/ah95H5QgXOpLcM9FtBvDDL+P84YYVRh0zPl1NgnST0/8JSi8QaeLCwgdcO2tJ12A4/HnkDAoW9cVZ+EJBvZ0Syj6TswaI3zJN
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
