apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: portainer-helm-chart-value-overrides
  namespace: portainer
data:
  values.yaml: |-
    persistence:
      enabled: true
    service:
      type: LoadBalancer
      httpPort: 9000
      httpNodePort: 30777
 
