---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      version: 2.X
  interval: 15m0s
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: portainer-helm-chart-value-overrides
  #     valuesKey: values.yaml
