apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actualserver
  namespace: budget
spec:
  chartref:
    kind: OCIRepository
    name: actualserver
    namespace: budget
  interval: 15m
  timeout: 5m
  values:
    replicaCount: 1
  # valuesFrom:
  # - kind: ConfigMap
  #   name: actualserver-helm-chart-value-overrides
  #   valuesKey: values.yaml # This is the default, but best to be explicit for clarity
