apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actualserver
  namespace: budget
spec:
  chartRef:
    kind: OCIRepository
    name: actualserver
    namespace: flux-system
  interval: 15m
  timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: actualserver-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
