apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-ingress-actual
  namespace: budget
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - actualserver
  defaultBackend:
    service:
      name: actual
      port:
        number: 5006
